### ISSUE TITLE
1

### ISSUE THREAD

**Issue by lonelyzou** [mayuxian/vue3-admin-template#1]
有个问题不知道算不算bug，按理来说点击用户管理的查看时，跳转到用户详情，这时左侧菜单的用户管理应该高亮的，因为用户详情应该是用户管理的子级

**Comment by mayuxian** [comment]
好提议~，非常感谢您的提议。这个我会加入TODO中的。

**Comment by mayuxian** [comment]
> 有个问题不知道算不算bug，按理来说点击用户管理的查看时，跳转到用户详情，这时左侧菜单的用户管理应该高亮的，因为用户详情应该是用户管理的子级

此问题已解决，并且修复了页面keepalive失效的问题。可查看提交记录进行更新。
